name: Build and push Bento base images
on:
  workflow_dispatch:

env:
  BUILD_ENV_FILE: "build.env"

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load build environment
        run: < ${{ env.BUILD_ENV_FILE }} >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image metadata for python-alpine
        id: meta-python-alpine
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bento-platform/bento_base_image
          tags:
            type=raw,value=python-alpine-latest
            type=raw,value=python-alpine-{{date 'YYYY.MM.DD.HHmm'}}

      - name: Build and push python-alpine image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./spec/python/alpine.Dockerfile
          build-args: |
            BENTO_PYTHON_VERSION=${{ env.BENTO_PYTHON_VERSION }}
            BENTO_ALPINE_VERSION=${{ env.BENTO_ALPINE_VERSION }}
          tags: ${{ steps.meta-python-alpine.outputs.tags }}
          labels: ${{ steps.meta-python-alpine.outputs.labels }}

      - name: Set up image metadata for python-debian
        id: meta-python-debian
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bento-platform/bento_base_image
          tags:
            type=raw,value=python-debian-latest
            type=raw,value=python-debian-{{date 'YYYY.MM.DD.HHmm'}}

      - name: Build and push python-debian image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./spec/python/debian.Dockerfile
          build-args: |
            BENTO_PYTHON_VERSION=${{ env.BENTO_PYTHON_VERSION }}
            BENTO_DEBIAN_VERSION=${{ env.BENTO_DEBIAN_VERSION }}
          tags: ${{ steps.meta-python-debian.outputs.tags }}
          labels: ${{ steps.meta-python-debian.outputs.labels }}
